### ISSUE TITLE
Error generating EDMX model

### ISSUE THREAD

**Issue by pmax101** [tombrothers/VfpEntityFrameworkProvider2#11]
Hello, I see the following error when generating a model from an existing VFP DB.

I guess the problem is with some table with a high column count that is hitting the limit of a VFP statement.

Unable to generate the model because of the following exception: 'System.Data.Entity.Core.EntityCommandExecutionException: An error occurred while executing the command definition. See the inner exception for details. ---> VfpClient.VfpException: SQL: Statement too long. ---> System.Data.OleDb.OleDbException: SQL: Statement too long.
   at System.Data.OleDb.OleDbCommand.ExecuteCommandTextErrorHandling(OleDbHResult hr)
   at System.Data.OleDb.OleDbCommand.ExecuteCommandTextForSingleResult(tagDBPARAMS dbParams, Object& executeResult)
   at System.Data.OleDb.OleDbCommand.ExecuteCommandText(Object& executeResult)
   at System.Data.OleDb.OleDbCommand.ExecuteCommand(CommandBehavior behavior, Object& executeResult)
   at System.Data.OleDb.OleDbCommand.ExecuteReaderInternal(CommandBehavior behavior, String method)
   at System.Data.OleDb.OleDbCommand.ExecuteReader(CommandBehavior behavior)
   at VfpClient.VfpCommand.<>c__DisplayClass1.<ExecuteDbDataReader>b__0(VfpCommand vfpCommand)
   at VfpClient.VfpCommand.<>c__DisplayClassf`1.<Execute>b__d()
   at VfpClient.VfpCommand.ExecuteWithoutTracing[T](Func`1 executeFunc)
   --- End of inner exception stack trace ---
   at VfpClient.VfpCommand.ExecuteWithoutTracing[T](Func`1 executeFunc)
   at VfpClient.VfpCommand.Execute[T](Func`2 executeFunc, VfpCommandMethod method)
   at VfpClient.VfpCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at VfpEntityFrameworkProvider.VfpOleDb.VfpCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable[] dataTables, Int32 startRecord, Int32 maxRecords, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable dataTable)
   at VfpEntityFrameworkProvider.Schema.SchemaManager.CreateDataTable(String commandText, VfpParameterCollection parameters)
   at VfpEntityFrameworkProvider.VfpOleDb.VfpCommand.<>c__DisplayClass1.<ExecuteDbDataReader>b__0(SchemaManager schemaManager)
   at VfpEntityFrameworkProvider.Schema.SchemaManager.Using(String connectionString, Action`1 action)
   at VfpEntityFrameworkProvider.VfpOleDb.VfpCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.<Reader>b__c(DbCommand t, DbCommandInterceptionContext`1 c)
   at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.Reader(DbCommand command, DbCommandInterceptionContext interceptionContext)
   at System.Data.Entity.Internal.InterceptableDbCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior)
   --- End of inner exception stack trace ---
   at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior)
   at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.Execute(EntityCommand entityCommand, CommandBehavior behavior)
   at System.Data.Entity.Core.EntityClient.EntityCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Entity.Design.VersioningFacade.ReverseEngineerDb.SchemaDiscovery.EntityStoreSchemaGeneratorDatabaseSchemaLoader.LoadDataTable[T](String sql, Func`2 orderByFunc, DataTable table, EntityStoreSchemaFilterObjectTypes queryTypes, IEnumerable`1 filters, String[] filterAliases)
   at Microsoft.Data.Entity.Design.VersioningFacade.ReverseEngineerDb.SchemaDiscovery.EntityStoreSchemaGeneratorDatabaseSchemaLoader.LoadTableDetails(IEnumerable`1 filters)
   at Microsoft.Data.Entity.Design.VersioningFacade.ReverseEngineerDb.SchemaDiscovery.EntityStoreSchemaGeneratorDatabaseSchemaLoader.LoadStoreSchemaDetails(IList`1 filters)
   at Microsoft.Data.Entity.Design.VisualStudio.ModelWizard.Engine.ModelGenerator.GetStoreSchemaDetails(StoreSchemaConnectionFactory connectionFactory)
   at Microsoft.Data.Entity.Design.VisualStudio.ModelWizard.Engine.ModelGenerator.CreateStoreModel()
   at Microsoft.Data.Entity.Design.VisualStudio.ModelWizard.Engine.ModelGenerator.GenerateModel(List`1 errors)
   at Microsoft.Data.Entity.Design.VisualStudio.ModelWizard.Engine.ModelBuilderEngine.GenerateModels(String storeModelNamespace, ModelBuilderSettings settings, List`1 errors)
   at Microsoft.Data.Entity.Design.VisualStudio.ModelWizard.Engine.ModelBuilderEngine.GenerateModel(ModelBuilderSettings settings, IVsUtils vsUtils, ModelBuilderEngineHostContext hostContext)'.
Loading metadata from the database took 00:01:21.8162844.
Generating the model took 00:08:34.1121004.

**Comment by mPisano** [comment]
The statement too long is typically when it uses all the fields as "Where" expressions to locate the row when it cant find the primary index, typically when Updating a row.
I've never seen it getting the model but your building an EDMX, where I used the Code First approach with the older EF5 reverse engineer tools and use the code first c# Schema classes with EF6 for CRUD.
You might want to try the Code First approach, or wait for Toms suggestions

**Comment by pmax101** [comment]
Thank you @mPisano I think you are on point. This is a large database with several tables with no keys. I tried the Code First approch and now I have a working model!

**Comment by cvivieca** [comment]
Any update about this issue using EDMX? I'm getting same error.

**Comment by cvivieca** [comment]
Any update about this issue using EDMX? I'm getting same error. I achieved get some models but I can't get more.

**Comment by mPisano** [comment]
I would again suggest the code first approach.

if you cant figure out why the SQL statement is too long turn on the trace listener in your app.config (below) and read the logs.

Regards,
Mike

`
<configuration>
    ....
  <system.diagnostics>
    <trace autoflush="true" />
    <sources>
      <source name="VfpClient" switchValue="All">
        <listeners>
          <add name="VfpClientTextWriterTraceListener" type="System.Diagnostics.TextWriterTraceListener" initializeData="C:\temp\VFPEFTrace.txt" />
        </listeners>
      </source>
    </sources>
  </system.diagnostics>
</configuration>
`

**Comment by cvivieca** [comment]
> I would again suggest the code first approach.
> 
> if you cant figure out why the SQL statement is too long turn on the trace listener in your app.config (below) and read the logs.
> 
> Regards,
> Mike
> 
> `<configuration> .... <system.diagnostics> <trace autoflush="true" /> <sources> <source name="VfpClient" switchValue="All"> <listeners> <add name="VfpClientTextWriterTraceListener" type="System.Diagnostics.TextWriterTraceListener" initializeData="C:\temp\VFPEFTrace.txt" /> </listeners> </source> </sources> </system.diagnostics> </configuration>`

Where should I configure the trace listener for listening at not runtime?. I have it on my app.config but actually my error is not at runtime it's updating the model.

What is the behavior behind when it's adding a new model?

Here a example: 
![image](https://user-images.githubusercontent.com/22035782/78717245-5281a880-78ee-11ea-9911-f76394dd4187.png)

**Comment by cvivieca** [comment]
> > I would again suggest the code first approach.
> > if you cant figure out why the SQL statement is too long turn on the trace listener in your app.config (below) and read the logs.
> > Regards,
> > Mike
> > `<configuration> .... <system.diagnostics> <trace autoflush="true" /> <sources> <source name="VfpClient" switchValue="All"> <listeners> <add name="VfpClientTextWriterTraceListener" type="System.Diagnostics.TextWriterTraceListener" initializeData="C:\temp\VFPEFTrace.txt" /> </listeners> </source> </sources> </system.diagnostics> </configuration>`
> 
> Where should I configure the trace listener for listening at not runtime?. I have it on my app.config but actually my error is not at runtime it's updating the model.
> 
> Here a example:
> ![image](https://user-images.githubusercontent.com/22035782/78717245-5281a880-78ee-11ea-9911-f76394dd4187.png)

What is the behavior behind when it's adding a new model?

**Comment by tombrothers** [comment]
@cvivieca  [SchemaManager](https://github.com/tombrothers/VfpEntityFrameworkProvider2/blob/master/Source/VfpEntityFrameworkProvider/Schema/SchemaManager.cs) is used to get the model information.  You could create a test program, using the configuration that Mike mentioned, for executing the calls to identify the source of the error.  The commands can be found in [StoreSchemaDefinition.ssdl.xml](https://github.com/tombrothers/VfpEntityFrameworkProvider2/blob/master/Source/VfpEntityFrameworkProvider/Resources/StoreSchemaDefinition.ssdl.xml).  They start with {{{|VFP:EF:SCHEMAHELPER_ and end with |}}}.  Additionally, you can see how SchemaManager in used in [VfpCommand.cs](https://github.com/tombrothers/VfpEntityFrameworkProvider2/blob/master/Source/VfpEntityFrameworkProvider/VfpOleDb/VfpCommand.cs).

**Comment by mPisano** [comment]
I'm not an expert in EDMX, but looking at your pic posted it seems you have all fields still marked as a KEYs? You must only include the fields for uniqueness or the SQL will overrun.  

![schema](https://user-images.githubusercontent.com/5075089/78893553-887f7380-7a39-11ea-8685-c6c56543e344.png)

**Comment by cvivieca** [comment]
Yes, It's because in that database nobody created primary keys. I solve that directly on **Entity Designer** table per table. Also I remove the DefinitionQuery from the EDMX file.  Before I map the same database with the same tables and it works.
