### ISSUE TITLE
Extremely slow query

### ISSUE THREAD

**Issue by pmax101** [tombrothers/VfpEntityFrameworkProvider2#12]
I have been using VFPOLEDB for quite some time and now trying to upgrade to EF6.

The problem I have is that the queries generated by the model are extremely slow compared to the standard ADO.net way. Here is an example:

**Query 1: Generated by the EF Model.**

SELECT 1 AS C1, E1.Idcustomer, E1.Name FROM Table1 E1 WHERE ("XXX" = E1.Type) AND (100 = E1.Number)

It takes this query more than 20 seconds to run even in the VFP native enviroment. Note the strange way in which the argument is before the column name used in the where section.

If I switch the order in which the parameters are selected I get this query:

**Query 2**

SELECT 1 AS C1, E1.Idcustomer, E1.Name FROM Table1 E1 WHERE (E1.Type= "XXX") AND (E1.Number = 100)

Which runs almost instantly.

I am kind of lost here. Thank you in advance.

**Comment by mPisano** [comment]
I have many large tables and they are read instantly! 

Most of the time slow queries are because of the lack of "Rushmore".... if your a FOX\VFP developer you remember the old "SET ORDER TO" days.... none of this applies...
there are two issues:
1) you need to loose any NDX's and use CDXs and make sure you have a primary\candidate KEYS and "WHERE"'s have Index's that are not be compound (ie multiple fields)
2) in a last bit of internationalism  VFP9 added non ASCII collating sequences to its engine and if you do not have the proper codepage set on your table(s) matching your connection string (see cpzero.prg\Disp Stat) rushmore will be disabled.
I typically make all tables now 1152 instead of 437 (ie windows\dos) and set that in the EF6 Connection string.
 
add name="DbfContext" providerName="VfpEntityFrameworkProvider2" connectionString="data source={0};deleted=True;null=False;enginebehavior=90;CODEPAGE=1252;"

Keep in mine my code replaces the {0} when creating the DBconext with the dbf path because I'm using free tables without a DBC... yes that old!

You can also try enginebehavior=80 and bypass the Codepage issues, but i'm not sure what newer SQL features are missing.

HTH
Mike

**Comment by tombrothers** [comment]
@pmax101 I'm familiar with the performance issue with having the value on the left side of the comparison which is I why I have an expression rewritter that should place the column reference on the left side of the comparison.  So I'm surprised to see that the sql command is getting written that way.  Could you send me a sample project to use to figure out why the rewritter isn't working correctly?

**Comment by pmax101** [comment]
@tombrothers yes. Here is a sample project, please notice you will have to adjust the db location in app.config.

https://we.tl/2wT8KCTzt8

You will see the query generated in the console. 

Thank you for your help!

**Comment by pmax101** [comment]
BTW, thanks @mPisano for the tips.

**Comment by mPisano** [comment]
I would of bet if I switch it to CodeFirst and lost the EDMX that it would behave better, but nope!

@tombrothers he is also using long field names so the DBC is necessary or the field names are truncated and the CDX bombs (I renamed the fields tested it as a free table and it still is Var = Field)

My Smaller "Code First" Test is attached, I have also removed all the tables from the DBC except one and @pmax101 check out the dynamic connection string creation - HTH.

I'm starting to lean back towards rushmore…. @pmax101 would be nice if you left the table data so we could test performance. looks like a list of provinces?

Mike

[Test.zip](https://github.com/tombrothers/VfpEntityFrameworkProvider2/files/2190535/Test.zip)

**Comment by pmax101** [comment]
@mPisano a couple of things:

- I don't have control over the Database, unfortunately this is a legacy system and all I can do is read from it.
- After detecting the problem I went straight to VFP9 console command window and executed those two queries from there, with very different results as posted. As Tom said, it seems that the query generated does not invert the order of the value and the parameter.
- Thank you for providing a sample project. I can see here the same problem indicated before. This is the resulting query:

SELECT TOP 1 
E1.Id_Provincia, 
E1.Nombre
FROM Provincias E1
WHERE (@__C2P__1) = E1.Id_Provincia 
ORDER BY E1.Id_Provincia

As the table is empty, you don't see a performance hit, but if you have thousands of rows, it takes for ever.

Thanks again for your help.

**Comment by tombrothers** [comment]
I created a new release that corrects this issue.

**Comment by mPisano** [comment]
Tom, 
Just wondering if this effects any of my queries, when would the expression not get flipped?

Does this have anything to do with Fox's NEAR and SET EXACT ON where 
"A"="ABC" would be .t.
"ABC"="A" would be .f.
 and 
"A"=="ABC" would always be .f.

Regards,
Mike

**Comment by tombrothers** [comment]
The change that I made ensures that the column is on the left side of the comparison. So, I guess that could affect a query configured in that manner. But this isn't the default configuration. It seems to me that it would be better to have your c# code use StartsWith to explicitly express your intent.

**Comment by pmax101** [comment]
Hi Tom, thanks for the update.

Unfortunately I am now seeing a weird issue. After updating to 2.0.6 I get an "Invalid Connection" exception regardless of the query. 

I if get back to 2.0.5 the connection works.

This is the stack trace:

Invalid Connection at VfpEntityFrameworkProvider.VfpProviderServices.ConvertToVfpConnection(DbConnection connection)
   at VfpEntityFrameworkProvider.VfpProviderServices.DbCreateDatabase(DbConnection connection, Nullable`1 commandTimeout, StoreItemCollection storeItemCollection)
   at System.Data.Entity.Core.Common.DbProviderServices.CreateDatabase(DbConnection connection, Nullable`1 commandTimeout, StoreItemCollection storeItemCollection)
   at System.Data.Entity.Core.Objects.ObjectContext.CreateDatabase()
   at System.Data.Entity.Migrations.Utilities.DatabaseCreator.Create(DbConnection connection)
   at System.Data.Entity.Migrations.DbMigrator.EnsureDatabaseExists(Action mustSucceedToKeepDatabase)
   at System.Data.Entity.Migrations.Infrastructure.MigratorBase.EnsureDatabaseExists(Action mustSucceedToKeepDatabase)
   at System.Data.Entity.Migrations.DbMigrator.Update(String targetMigration)
   at System.Data.Entity.Migrations.Infrastructure.MigratorBase.Update()
   at System.Data.Entity.Internal.DatabaseCreator.CreateDatabase(InternalContext internalContext, Func`3 createMigrator, ObjectContext objectContext)
   at System.Data.Entity.Internal.InternalContext.CreateDatabase(ObjectContext objectContext)
   at System.Data.Entity.Database.Create(Boolean skipExistsCheck)
   at System.Data.Entity.CreateDatabaseIfNotExists`1.InitializeDatabase(TContext context)
   at System.Data.Entity.Internal.InternalContext.<>c__DisplayClasse`1.<CreateInitializationAction>b__d()
   at System.Data.Entity.Internal.InternalContext.PerformInitializationAction(Action action)
   at System.Data.Entity.Internal.InternalContext.PerformDatabaseInitialization()
   at System.Data.Entity.Internal.LazyInternalContext.<InitializeDatabase>b__4(InternalContext c)
   at System.Data.Entity.Internal.RetryAction`1.PerformAction(TInput input)
   at System.Data.Entity.Internal.LazyInternalContext.InitializeDatabaseAction(Action`1 action)
   at System.Data.Entity.Internal.LazyInternalContext.InitializeDatabase()
   at System.Data.Entity.Internal.InternalContext.Initialize()
   at System.Data.Entity.Internal.InternalContext.GetEntitySetAndBaseTypeForType(Type entityType)
   at System.Data.Entity.Internal.Linq.InternalSet`1.Initialize()
   at System.Data.Entity.Internal.Linq.InternalSet`1.get_InternalContext()
   at System.Data.Entity.Infrastructure.DbQuery`1.System.Linq.IQueryable.get_Provider()
   at System.Linq.Queryable.Select[TSource,TResult](IQueryable`1 source, Expression`1 selector)

**Comment by mPisano** [comment]
I can confirm it works ok for me - I haven't exercised all my queries, but nothing negative yet.

Test.zip code works too:
SELECT TOP 1 
E1.Id_Provincia, 
E1.Nombre
FROM Provincias E1
WHERE E1.Id_Provincia = (@__C2P__1)
ORDER BY E1.Id_Provincia

From the Exception dump i see Migrations & CreateDatabase...
Are you sure your connect string is correct? 
This provider does not support migrations - you also need to set 
Database.SetInitializer<eiffelEntitites>(null);

HTH,
Mike

**Comment by pmax101** [comment]
Hi Mike,

Yes, that is weird, I am not doing anything besides creating the Code First model from the database. The connection string is standard, only the location of the DBC.

I dont know why its trying to create the database.

It does not happen in version 2.0.5 of the provider.

**Comment by pmax101** [comment]
@mPisano Thank again for your help! I was not setting the initializer to null. (Apparently if defaulted to null in 2.0.5?)

Works like charm now. 200 ms a single seek in a database with a million rows. 

Amazing work Tom!

**Comment by mPisano** [comment]
Great News!,
and Yes - Amazing work Tom
